O NumPy é uma biblioteca de código aberto para a linguagem de programação Python, que é usada principalmente para computação científica e análise de dados. O NumPy é projetado para trabalhar com matrizes e vetores, tornando-o uma ferramenta poderosa para tarefas como processamento de imagens, aprendizado de máquina e outras áreas de ciência de dados.

np.array(): A função np.array() é usada para criar arrays NumPy. Ela pode receber uma lista Python ou uma sequência como entrada e retorna um array NumPy.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


Indexação e slicing:
Você pode acessar elementos específicos de um array NumPy usando a indexação. Por exemplo, a[0] retorna o primeiro elemento do array a. Você também pode usar o slicing para acessar subconjuntos do array, por exemplo, a[1:3] retorna uma nova matriz contendo os elementos 2 e 3 de a.

np.arange(): A função np.arange() é usada para criar um array com valores espaçados uniformemente dentro de um intervalo especificado. Por exemplo, np.arange(0, 10, 2) cria um array com valores 0, 2, 4, 6 e 8.

In [ ]:
# Criando um array com valores espaçados uniformemente
c = np.arange(0, 10, 2)
print(c)  # output: [0 2 4 6 8]

[0 2 4 6 8]


np.linspace(): A função np.linspace() é usada para criar um array com valores espaçados uniformemente entre dois limites. Por exemplo, np.linspace(0, 1, 5) cria um array com valores 0, 0.25, 0.5, 0.75 e 1.

In [ ]:
# Criando um array com valores espaçados uniformemente entre dois limites
d = np.linspace(0, 1, 5)
print(d)  # output: [0.   0.25 0.5  0.75 1.  ]

[0.   0.25 0.5  0.75 1.  ]


np.zeros() e np.ones(): As funções np.zeros() e np.ones() são usadas para criar arrays de zeros e uns, respectivamente, com a forma especificada. Por exemplo, np.zeros((3, 4)) cria um array de zeros com a forma 3x4.

In [ ]:
# Criando um array de zeros com forma 3x4
e = np.zeros((3, 4))
print(e)

# Criando um array de uns com forma 2x2x2
f = np.ones((2, 2, 2))
print(f)

np.random.rand(): A função np.random.rand() é usada para criar um array de números aleatórios uniformemente distribuídos entre 0 e 1 com a forma especificada. Por exemplo, np.random.rand(2, 3) cria um array de 2x3 com números aleatórios.

In [ ]:
# Criando um array de números aleatórios uniformemente distribuídos
# entre 0 e 1 com forma 2x3
g = np.random.rand(2, 3)
print(g)

[[0.4876336  0.67037529 0.27268246]
 [0.37398026 0.18575964 0.42623253]]


np.reshape(): A função np.reshape() é usada para reorganizar o formato de um array. Por exemplo, np.reshape(a, (2, 3)) reorganiza o array a em uma matriz de 2x3.

In [ ]:
# Reorganizando o formato de um array
h = np.array([[1, 2, 3], [4, 5, 6]])
i = np.reshape(h, (3, 2))
print(i)

[[1 2]
 [3 4]
 [5 6]]


np.max(), np.min(), np.mean() e np.std(): As funções np.max(), np.min(), np.mean() e np.std() são usadas para calcular o valor máximo, mínimo, média e desvio padrão de um array NumPy, respectivamente.

In [ ]:
# Calculando o valor máximo, mínimo, média e desvio padrão de um array
j = np.array([1, 2, 3, 4, 5])
print(np.max(j))    # output: 5
print(np.min(j))    # output: 1
print(np.mean(j))   # output: 3.0
print(np.std(j))    # output: 1.41421356

5
1
3.0
1.4142135623730951


np.dot(): A função np.dot() é usada para realizar a multiplicação de matrizes. Por exemplo, np.dot(a, b) realiza a multiplicação de matrizes entre os arrays a e b.

In [ ]:
# Realizando a multiplicação de matrizes entre dois arrays
k = np.array([[1, 2], [3, 4]])
l = np.array([[5, 6], [7, 8]])
m = np.dot(k, l)
print(m)

[[19 22]
 [43 50]]


np.transpose(): A função np.transpose() é usada para transpor um array. Por exemplo, np.transpose(a) transpõe o array a.

In [ ]:
# Transpondo um array
n = np.array([[1, 2], [3, 4]])
o = np.transpose(n)
print(o)

[[1 3]
 [2 4]]


In [ ]:

a = np.array([1, 2, 3])      # array de uma dimensão
b = np.array([[1, 2, 3], [4, 5, 6]])  # array de duas dimensões
c = np.zeros((3, 4))         # array de zeros de 3x4
d = np.ones((2, 3))          # array de uns de 2x3
e = np.random.rand(2, 3)     # array de números aleatórios de 2x3


In [ ]:

a = np.array([1, 2, 3, 4, 5, 6])
b = np.reshape(a, (2, 3))  # reshape para um array de 2x3


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate([a, b])     # combinar os arrays a e b
d = np.stack([a, b])            # empilhar os arrays a e b verticalmente
